export const siteConfig = {
  name: "Bolunga Systems",
  title: "Bolunga Systems | Enterprise Technology Solutions Across Africa",
  description:
    "Bolunga Systems delivers enterprise-grade technology consulting, cybersecurity, telecommunications, and digital transformation solutions. Over 12 years of experience, 2600+ projects delivered across 9 countries.",
  url: "https://www.bolunga.co.za",
  ogImage: "/image/og-image.jpg",
  author: "Bolunga Systems",
  phone: "+27 11 207 3904",
  phoneRaw: "+27112073904",
  email: "info@bolunga.co.za",
  address: {
    line1: "Unit 5 Platinum Close",
    line2: "Midrand, SA",
  },
  keywords: [
    "Bolunga Systems",
    "Technology Consulting",
    "Cybersecurity South Africa",
    "Telecommunications",
    "Fibre Connectivity",
    "AI Training",
    "Database Management",
    "E-Waste Management",
    "Digital Transformation Africa",
    "Enterprise IT Solutions",
    "Pan-African Technology",
    "Systems Integration",
  ],
  social: {
    facebook: "https://www.facebook.com/share/1ABuRRrkmW/?mibextid=wwXIfr",
    linkedin: "https://www.linkedin.com/company/bolunga-systems",
    instagram: "https://www.instagram.com/bolunga_systems",
    twitter: "https://x.com/BolungaSys52013?t=f1KG8o4_j27WwnLlGm-Umw&s=03",
  },
  navigation: [
    { label: "Home", href: "/" },
    { label: "About", href: "/about" },
    { label: "Services", href: "/services" },
    { label: "Contact", href: "/contact" },
  ],
  services: [
    { label: "Technology Consulting", href: "/technology-consulting" },
    { label: "Cybersecurity", href: "/services" },
    { label: "Telecommunications", href: "/telecommunications-fibre" },
    { label: "Tracking Systems", href: "/tracking-systems" },
    { label: "Web Development", href: "/web-development" },
    { label: "AI Training", href: "/services" },
    { label: "Database Management", href: "/services" },
    { label: "E-Waste Management", href: "/services" },
  ],
};
